//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_border_H
#define METASPRITE_border_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define border_TILE_ORIGIN 0
#define border_TILE_W 8
#define border_TILE_H 8
#define border_WIDTH 160
#define border_HEIGHT 144
#define border_TILE_COUNT 9
#define border_MAP_ATTRIBUTES 0
extern const unsigned char border_map[360];
#define border_map_attributes border_map

BANKREF_EXTERN(border)

extern const uint8_t border_tiles[144];

#endif
