//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gt_invert_H
#define METASPRITE_gt_invert_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gt_invert_TILE_ORIGIN 0
#define gt_invert_TILE_W 8
#define gt_invert_TILE_H 8
#define gt_invert_WIDTH 8
#define gt_invert_HEIGHT 8
#define gt_invert_TILE_COUNT 1
#define gt_invert_MAP_ATTRIBUTES 0
extern const unsigned char gt_invert_map[1];
#define gt_invert_map_attributes gt_invert_map

BANKREF_EXTERN(gt_invert)

extern const uint8_t gt_invert_tiles[16];

#endif
