//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_testbar_bw_H
#define METASPRITE_testbar_bw_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define testbar_bw_TILE_ORIGIN 0
#define testbar_bw_TILE_W 8
#define testbar_bw_TILE_H 8
#define testbar_bw_WIDTH 128
#define testbar_bw_HEIGHT 8
#define testbar_bw_TILE_COUNT 4
#define testbar_bw_MAP_ATTRIBUTES 0
extern const unsigned char testbar_bw_map[16];
#define testbar_bw_map_attributes testbar_bw_map

BANKREF_EXTERN(testbar_bw)

extern const uint8_t testbar_bw_tiles[64];

#endif
