//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_testbar_color_H
#define METASPRITE_testbar_color_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define testbar_color_TILE_ORIGIN 0
#define testbar_color_TILE_W 8
#define testbar_color_TILE_H 8
#define testbar_color_WIDTH 128
#define testbar_color_HEIGHT 8
#define testbar_color_TILE_COUNT 2
#define testbar_color_MAP_ATTRIBUTES 0
extern const unsigned char testbar_color_map[16];
#define testbar_color_map_attributes testbar_color_map

BANKREF_EXTERN(testbar_color)

extern const uint8_t testbar_color_tiles[32];

#endif
